export default {
	GET_REPO_DATA_SUCCESS: 'GET_REPO_DATA_SUCCESS',
	GET_REPO_DATA_ERROR: 'GET_REPO_DATA_ERROR',

	HIDE_SPINNER: 'HIDE_SPINNER',
	SHOW_SPINNER: 'SHOW_SPINNER',

	GET_REPO_LANGUAGES_SUCCESS: "GET_REPO_LANGUAGES_SUCCESS",
	GET_REPO_LANGUAGES_FAILURE: "GET_REPO_LANGUAGES_FAILURE",

	GET_REPO_CONTRIBUTORS_SUCCESS: "GET_REPO_CONTRIBUTORS_SUCCESS",
	GET_REPO_CONTRIBUTORS_FAILURE: "GET_REPO_CONTRIBUTORS_FAILURE"
};
